# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/div_gen_0/div_gen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==div_gen_0 || ORIG_REF_NAME==div_gen_0} -quiet] -quiet
