# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xcku5p-ffvb676-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/pedro/Documents/arm7/tcc-arm7.cache/wt [current_project]
set_property parent.project_path C:/Users/pedro/Documents/arm7/tcc-arm7.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:kcu116:part0:1.0 [current_project]
set_property ip_output_repo c:/Users/pedro/Documents/arm7/tcc-arm7.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv C:/Users/pedro/Documents/arm7/tcc-arm7.srcs/sources_1/new/extend.sv
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}

synth_design -top extend -part xcku5p-ffvb676-2-e


write_checkpoint -force -noxdef extend.dcp

catch { report_utilization -file extend_utilization_synth.rpt -pb extend_utilization_synth.pb }
