set_property SRC_FILE_INFO {cfile:C:/RTDDoS/Detection/Hardware/arm7/tcc-arm7.srcs/constrs_2/Nexys-4-DDR-Master.xdc rfile:../../../tcc-arm7.srcs/constrs_2/Nexys-4-DDR-Master.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {c1/cycle[0]} -source [get_ports clk] -divide_by 1 [get_pins {c1/FSM_sequential_cycle_reg[0]/Q}]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {c1/cycle[1]} -source [get_ports clk] -divide_by 1 [get_pins {c1/FSM_sequential_cycle_reg[1]/Q}]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {c1/cycle[2]} -source [get_ports clk] -divide_by 1 [get_pins {c1/FSM_sequential_cycle_reg[2]/Q}]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {c1/cycle[3]} -source [get_ports clk] -divide_by 1 [get_pins {c1/FSM_sequential_cycle_reg[3]/Q}]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {c1/cycle[4]} -source [get_ports clk] -divide_by 1 [get_pins {c1/FSM_sequential_cycle_reg[4]/Q}]
